### PR TITLE
Auto

### PR DESCRIPTION
**Pull request by saqzari**
I managed to allow all auto laws dependent included to be used when automating. I also found a way to classify folds and unfolds. Please have a look in case I classified it wrong

### CODE REVIEW

**Comment by saqzari** [comment]
Also, could you go into more detail on how I should apply folds and unfolds when using the automate command? Are they applied similarly to applySimp?

**Comment by andrewbutterfield** [comment]
Yes, they behave in the same way - keep going until none apply.

**Comment by saqzari** [comment]
But what would be the difference between fold and unfold? Is it similarly
to simp and comp?

**Comment by saqzari** [comment]
Added alternate auto commands for folds and unfolds

**Comment by andrewbutterfield** [comment]
the fold/unfold laws should be different, but you are right, in most cases a definition law is a simplifer when used as a fold, and a complexifier when used as an unfold.  

Now that the classification is working, I can see how we need to "tweak" things.

1.  When you have all the simps, folds and unfolds determined, then remove any laws from simps that are fold/unfold.
    (Or, classify fold/unfold first, then only try to classify a law as simp if not in the fold/unfold list.
2. We need to tighten up the condition for being a definition. At the moment, the law `P /\ Q === Q /\ P` is classified as fold/unfold Incorrectly) and not as a simplifier (which is correct). 

Revised check - a law  `P === Q` is a definition (left-to-right) if:

- `P` has the form `Cons N [V1,..,VN]` where `N>0` and each `Vi` is a variable
- `Q` does **not** have the form `Cons N [...]`, with the same name `N`.

**Comment by saqzari** [comment]
In terms of the haskell what is the N in Cons N? In the code, it has the
form "Cons tk sb n ts"

**Comment by saqzari** [comment]
Hello, I made some commits that remove simps that are unfolds/folds and also did the revised check for unfold/fold classification. I'm unsure if the revised check is correct on my end so a look-through would be greatly appreciated.

**Comment by andrewbutterfield** [comment]
yes

--------------------------------------------------------------------
Andrew Butterfield     Tel: +353-1-896-2517     Fax: +353-1-677-2204
***@***.***, Head of Software Foundations & Verification Research Group
School of Computer Science and Statistics,
Room G.39, O'Reilly Institute, Trinity College, University of Dublin
                         http://www.scss.tcd.ie/Andrew.Butterfield/
--------------------------------------------------------------------


From: saqzari ***@***.***>
Reply to: andrewbutterfield/reasonEq ***@***.***>
Date: Wednesday 29 March 2023 at 14:17
To: andrewbutterfield/reasonEq ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [andrewbutterfield/reasonEq] Auto (PR #11)

But what would be the difference between fold and unfold? Is it similarly
to simp and comp?

**Comment by andrewbutterfield** [comment]
it’s the `n`

--------------------------------------------------------------------
Andrew Butterfield     Tel: +353-1-896-2517     Fax: +353-1-677-2204
***@***.***, Head of Software Foundations & Verification Research Group
School of Computer Science and Statistics,
Room G.39, O'Reilly Institute, Trinity College, University of Dublin
                         http://www.scss.tcd.ie/Andrew.Butterfield/
--------------------------------------------------------------------


From: saqzari ***@***.***>
Reply to: andrewbutterfield/reasonEq ***@***.***>
Date: Wednesday 29 March 2023 at 19:22
To: andrewbutterfield/reasonEq ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [andrewbutterfield/reasonEq] Auto (PR #11)

In terms of the haskell what is the N in Cons N? In the code, it has the
form "Cons tk sb n ts"

**Comment by saqzari** [comment]
Alright cool, I assumed so, you can find those in the commits I recently
pushed

**Comment by andrewbutterfield** [comment]
This is all looking good.

Two things:
 1. I've changed the definition of implication so it is now classifed as a definition properly (commit [3914906] on the `auto` branch). You do a `git pull` to get this change.
 2. There is one more tweak to the fold/unfold check. We also need to require that the variable list on the LHS has unique variables (none repeated). The problem is the law `P \/ P === P`, which should be a left-to-right simplifier. So we to add a unique variable check to `isFold`. I will update the classification document I wrote to reflect this.

**Comment by andrewbutterfield** [comment]
I have found a situation where a definition can be used to do unfold,
but we might not want to use it to fold. So keeping two lists is a good idea.

Consider `f(x,y) = x + 2`.

Unfold: `f(1,10)` becomes `1+2`.

Fold: `1+2` becomes `f(1,?)`.

**Comment by saqzari** [comment]
So what would be the best way to distinguish between them?

**Comment by saqzari** [comment]
> This is all looking good.
> 
> Two things:
> 
> 1. I've changed the definition of implication so it is now classifed as a definition properly (commit [[3914906](https://github.com/andrewbutterfield/reasonEq/commit/3914906f6ddd210375e97c0d2130717484c4d666)] on the `auto` branch). You do a `git pull` to get this change.
> 2. There is one more tweak to the fold/unfold check. We also need to require that the variable list on the LHS has unique variables (none repeated). The problem is the law `P \/ P === P`, which should be a left-to-right simplifier. So we to add a unique variable check to `isFold`. I will update the classification document I wrote to reflect this.

Alright, I have just committed a change that checks if the variables are unique or not

**Comment by andrewbutterfield** [comment]
The classification is good - still that last tweak regarding identifying problematic folds,
but park that for a moment.

There is a problem with `au u`. It should only work with matches that match on the LHS. 
If I classify in the `UTPBase` theory, then law `⊒_def` is classified correctly as fols/unfold.

Consider this partial proof for conjecture 1,  `⊒_∨_distr`. I focus on the lhs
and then issue the `au u` command *twice*. The first works as it should,
but the second is wrong - it's actually doing a fold. An unfold only applies laws that match the lhs. The second match is one for the rhs and should not be used here.

```
Proof for sqsupseteq_lor_distr
	(P∨Q⊒R)  ≡  (P⊒R)∧(Q⊒R)  ⊤
by reduce
(P∨Q⊒R)≡(P⊒R)∧(Q⊒R)
   = 'match-lhs ⊒_def@[1]'
[P∨Q⟹  R]≡(P⊒R)∧(Q⊒R)
   = 'match-rhs ⊒_def@[1]'
 ...
⊢
(P∨Q⊒R)≡(P⊒R)∧(Q⊒R)    ⊤
```

**Comment by saqzari** [comment]
Oh oops, for some reason, I set the checking functions wrong. Should be
fine now. Just committed and pushed

**Comment by andrewbutterfield** [comment]
Looks good. I'll accept this.

**Comment by saqzari** [comment]
Cool, is there anything else that should be done?

**Pull request merged**
