### PR TITLE
Simplification

### PR DESCRIPTION
**Pull request by saqzari**
Here is what I have so far. I tried a method where all matching simplifications are gathered and then each one is applied until success is achieved. However, when using the command, it somehow completed the conjecture instantly and every other conjecture in the theory. It might be because of the applyFocus but not a hundred percent sure. If you have the time, could you have a look? Thank you

### CODE REVIEW

**Comment by saqzari** [comment]
> Here is what I have so far. I tried a method where all matching simplifications are gathered and then each one is applied until success is achieved. However, when using the command, it somehow completed the conjecture instantly and every other conjecture in the theory. It might be because of the applyFocus but not a hundred percent sure. If you have the time, could you have a look? Thank you

Actually, after testing it again, it seems it didn't occur and seems to be working fine. I'll try to see if I can replicate the previous error

**Comment by andrewbutterfield** [comment]
Your code has a left-to-right bug - you are applying simplifiers the wrong way around
[auto-bugs.txt](https://github.com/andrewbutterfield/reasonEq/files/10930836/auto-bugs.txt)

**Comment by saqzari** [comment]
Hello, do you know which part of the code controls that?

**Comment by andrewbutterfield** [comment]
Given a match, you need to look at its `MatchClass` component.
This is defined in `Proofs.lhs` as
```
data MatchClass
  = MA       -- match all of law, with replacement 'true'
  | MEL      -- match binary equivalence lhs
  | MER      -- match binary equivalence rhs
  | ME [Int] -- match subpart of 'equiv' chain, length > 2
  | MIA      -- match implication antecedent A, replacement A /\ C
  | MIC      -- match implication consequent C, replacement A \/ C
  -- MEV should be last, so these matches rank low by default
  | MEV Int  -- match PredVar at given position
  deriving (Eq,Ord,Show,Read)
```
You are only interested in `MEL` and `MER`.
A rule that simplifes left-to-right means you only apply a `MEL` match.

**Comment by saqzari** [comment]
Would I have to change the matchclass of the match before applying? Is
there a function for that?

**Comment by saqzari** [comment]
I made it so the matchclass is changed depending on the direction. However, I am unable to test it from my side as I am unable to resume a liveproof anymore and I don't know how to reset everything

**Comment by andrewbutterfield** [comment]
No - you do not change the matchclass of a match - it tells you what part of the law was matched.

When you get a match you check that is has the right matchclass - if so you can use it,
of not, you reject it and move on.

**Comment by saqzari** [comment]
Alright, I’ll make the change as soon as I can. I also sent some emails
regarding the main written dissertation in case you haven’t seen them yet

**Comment by saqzari** [comment]
> No - you do not change the matchclass of a match - it tells you what part of the law was matched.
> 
> When you get a match you check that is has the right matchclass - if so you can use it, of not, you reject it and move on.

Alright, it should be fixed now and I have it committed. Do you know how I can reset everything on my side instead of having to delete ReasonEq and reinstall so I will be able to test it?

**Comment by saqzari** [comment]
I changed the formation of applySimp so it goes through everything on one simplifier first (match, apply, etc.) before moving on to the next without storing anything which might fix the liveproof issue you mentioned before. I also added an "au c" command which uses checkisComp instead of checkisSimp.

**Comment by andrewbutterfield** [comment]
I've just added the facility to save/load autolaws to the prover.

You should do the following to get them setup for theories `Equiv`...`AndOrInvert`:
```
$ req -d
🛠devproj.Equiv> load
```
I have presaved them in the `devproj` folder, accessed when you start `req` with the `-d` option.

**Comment by saqzari** [comment]
> I've just added the facility to save/load autolaws to the prover.
> 
> You should do the following to get them setup for theories `Equiv`...`AndOrInvert`:
> 
> ```
> $ req -d
> 🛠devproj.Equiv> load
> ```
> 
> I have presaved them in the `devproj` folder, accessed when you start `req` with the `-d` option.

Alright cool. Are my changes to applySimp alright?

**Comment by andrewbutterfield** [comment]
Your changes look OK but I don't see anything happening. YOu need somewhay to show laws being matched even if they fail. Use `pdbg` to do this

**Comment by saqzari** [comment]
> Your changes look OK but I don't see anything happening. YOu need somewhay to show laws being matched even if they fail. Use `pdbg` to do this

Hello, I added some debug code that shows the law names currently attempting to be matched. Also, another question, are there more steps after this? Is there enough to show off for the presentation?

**Comment by andrewbutterfield** [comment]
How do you test this?

I tried it - going into Implies theory and setting up proof of conj 2 using `reduce`.
When I do `au` or `au c` I don't see any debug output!
If I focus on P/\Q term I expect  `au c` to do something.

**Comment by saqzari** [comment]
> How do you test this?
> 
> I tried it - going into Implies theory and setting up proof of conj 2 using `reduce`. When I do `au` or `au c` I don't see any debug output! If I focus on P/\Q term I expect `au c` to do something.

I tested it on And and redtail like before. I tried using implies, it seems to work fine but only after there are simplifiers available as I had to Assume ., classify .

**Comment by andrewbutterfield** [comment]
Can you show me:
1. detailed steps to get it going - take from starting the prover through to the result - how do you use Assume, classify (note that this is already done and saved for all theories before Implies. How/when do you start the proof.
2. A screenshot or cut-n-paste from the terminal

I cannot observe anything happening other than scrolling up to see the message:
```
No successful matching simp applys
```

**Comment by saqzari** [comment]
> Can you show me:
> 
> 1. detailed steps to get it going - take from starting the prover through to the result - how do you use Assume, classify (note that this is already done and saved for all theories before Implies. How/when do you start the proof.
> 2. A screenshot or cut-n-paste from the terminal
> 
> I cannot observe anything happening other than scrolling up to see the message:
> 
> ```
> No successful matching simp applys
> ```
Is this happening only for Implies or for everything else?

**Comment by saqzari** [comment]
> Can you show me:
> 
> 1. detailed steps to get it going - take from starting the prover through to the result - how do you use Assume, classify (note that this is already done and saved for all theories before Implies. How/when do you start the proof.
> 2. A screenshot or cut-n-paste from the terminal
> 
> I cannot observe anything happening other than scrolling up to see the message:
> 
> ```
> No successful matching simp applys
> ```

image

**Comment by saqzari** [comment]
> > Can you show me:
> > 
> > 1. detailed steps to get it going - take from starting the prover through to the result - how do you use Assume, classify (note that this is already done and saved for all theories before Implies. How/when do you start the proof.
> > 2. A screenshot or cut-n-paste from the terminal
> > 
> > I cannot observe anything happening other than scrolling up to see the message:
> > ```
> > No successful matching simp applys
> > ```
> 
> image

This is for Equiv. I only applied pdbg to one line in applySimps. It can be seen in the commit

**Comment by andrewbutterfield** [comment]
How do you start the program? `req`  or `req -d`.
What theories do you do `Assume` and `classify` in?
How do you setup the proof? None of the screenshots above answer these Qs.

I suggest you do `req -d`, set everything up, including the proof, and check it works.
Then exist the proof without abandoning it. Do a `save` command, then `quit`, and then commit and push to `auto`.
I can then pull, so I get your setup.

**Comment by andrewbutterfield** [comment]
I played around a bit and got it to work.

However `au c` is not working and it should.  I setup a proof for `equiv_subst`.  I would expect `equiv_id` to match anything when run backwards. You need to figure this out.

I've pushed a test setup to `auto` that has only two simp classifiers - you can use this to debug why `au c` is not working when it should.

**Comment by saqzari** [comment]
Alright, thank you, I'll have a look as soon as I can. Here is what the
presentation looks like so far if you want to have a look at it

**Comment by saqzari** [comment]
Hello, I decided to fix the classify * command, basing it off assume *. It should work normally now

**Comment by andrewbutterfield** [comment]
Progress worth saving

**Pull request merged**
